[template]
cargo_generate_version = ">=0.9.0"
ignore = []
exclude = []

[placeholders]

[hooks]
init = ["./hooks/set-variables.rhai"]
post = ["./hooks/build.rhai", "./hooks/cleanup.rhai"]

# Base project
project_name = { prompt = "📦 Project name", type = "string" }

# Optional Library Crate Name
lib_name = { prompt = "📚 Library crate name (leave empty to skip lib crate)", default = "", type = "string" }
lib_crate_name = { prompt = "📁 Library crate path (defaults to project_name if empty)", default = "", type = "string" }
lib_crate_display_name = { prompt = "🖹 Library display name (e.g. MyApp Core)", default = "", type = "string" }

# Optional Binary Crate Name
bin_name = { prompt = "🔧 Binary crate name (leave empty to skip bin crate)", default = "", type = "string" }
bin_crate_name = { prompt = "📁 Binary crate path (defaults to project_name if empty)", default = "", type = "string" }
bin_crate_display_name = { prompt = "🖹 Binary display name (e.g. MyApp CLI)", default = "", type = "string" }

# Executable
exe_name = { prompt = "🚀 Executable name (defaults to project_name if empty)", default = "", type = "string" }

# Description
description = { prompt = "📝 Project description", default = "A blazing fast Rust CLI tool.", type = "string" }

# Licensing
license_year = { prompt = "📅 License year", default = "{{__year__}}", type = "string" }
license_holder = { prompt = "👤 License holder", default = "{{authors}}", type = "string" }
