# In your cargo-generate.toml or clap-config.toml

[template]
cargo_generate_version = ">=0.9.0"
ignore = []
exclude = []

[hooks]
pre = ["hooks/set-variables.rhai"]
post = ["hooks/build.rhai", "hooks/cleanup.rhai"]
